apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: h735c00w8-go
  janus-idp.io/tekton: h735c00w8-go
  backstage.io/kubernetes-id: h735c00w8-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h735c00w8-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
